version: "3.8"

services:
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb_server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - imgdata:/data/db
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=admin
      - DB_PASSWORD=secret
      - MONGO_PORT=27017
      - MONGO_DB=image_emotion_db
    depends_on:
      - db
  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
volumes: 
  imgdata:
