version: "3.8"

services:
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb_server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - imgdata:/data/db
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - db
  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_DB=${MONGO_DB}
    depends_on:
      - db
volumes: 
  imgdata:
