name: Machine Learning Client CI
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # update version(s) as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          cd machine-learning-client
          pipenv sync --dev
          pipenv shell

      - name: Test with pytest
        run: |
          pipenv run pytest test_mlc_deepface.py
